name: backfill_pipeline
networks:
  redpanda_network:
    name: redpanda_network
    driver: bridge
services:
  trade-producer:
    container_name: trade-producer
    build:
      context: ../services/trade_producer
    networks:
      - redpanda_network
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda-0:9092
      - LIVE_OR_HISTORICAL=historical
      - LAST_N_DAYS=7

  trade-to-ohlc:
    container_name: trade-to-ohlc
    build:
      context: ../services/trade_to_ohlc
    networks:
      - redpanda_network
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda-0:9092
      - OHLC_WINDOWS_SECONDS=60

  kafka-to-feature-store:
    container_name: kafka-to-feature-store
    build:
      context: ../services/kafka_to_feature_store
    networks:
      - redpanda_network
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda-0:9092
      - LIVE_OR_HISTORICAL=historical
      - BUFFER_SIZE=1440
